version: '3.8'

services:
  go-app:
    build:
      context: ./Go-Order-Food/Dockerfile
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  next-app:
    build:
      context: ./path/to/nextjs-project
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  wordpress:
    build:
      context: ./path/to/wordpress-project
      dockerfile: Dockerfile
    ports:
      - '80:80'
